### ISSUE TITLE
Crash when right clicking the modular boat with yungsbetterportals

### ISSUE THREAD

**Issue by zEpiixz** [BrassGoggledCoders/Transport#35] opened 2021-02-26 10:23 UTC
https://pastebin.com/cVCS7nAZ

**Comment by SkySom** [comment] 2021-02-26 17:04
Duplicate of #34, See also: https://github.com/yungnickyoung/YUNGs-Better-Portals/issues/14

**Closed as completed by SkySom** 2021-02-26 17:04 UTC
Labels: Duplicate
