### ISSUE TITLE
Clash with Create in JEI

### ISSUE THREAD

**Issue by Nachtflame** [BrassGoggledCoders/Transport#24] opened 2021-01-14 21:07 UTC
Forge [forge-35.1.36]
Create [create-mc1.16.3_v0.3e]
Transport [Transport-1.16.4-3.4.0]
   Patchouli [Patchouli-1.16.4-48]
   Titanium [titanium-1.16.4-3.2.5]
JEI [jei-1.16.4-7.6.1.65]

Updated Transport from 3.3.1, and suddenly Mechanical Crafting recipes from Create no longer display in JEI.  Have verified that with 3.3.1 they DO still show. Recipes still function, just don't display.
Attaching logs from instance with ONLY mods listed above, where issue persists
[latest.log](https://github.com/BrassGoggledCoders/Transport/files/5816997/latest.log)
[debug.log](https://github.com/BrassGoggledCoders/Transport/files/5816998/debug.log)

**Comment by SkySomDynata** [comment] 2021-01-14 21:08
Duplicate of #21

**Comment by SkySom** [comment] 2021-01-14 21:09
Duplicate of #21

**Closed as completed by SkySom** 2021-01-14 21:09 UTC

**Comment by Nachtflame** [comment] 2021-01-14 21:10
Whoops, guess I should have looked past the title of that one. I'll await the update then.

**Comment by SkySom** [comment] 2021-01-14 21:11
Yep, the issue is I don't add a bucket, but don't return the proper answer for having one. It's high priority for me to fix, just keepnot being able to.
